AWSTemplateFormatVersion: '2010-09-09'
Description: Sets ups Cloudtrail logging to Sumologic.

Parameters:

  SumoLogicId:
    Type: String
    Description: External ID for Sumologic, in format of SumoDeployment:SumoAccountId

  SumoLogicAccountID:
    Type: String
    Description: Account ID of Sumologic to use
    Default: 926226587429

Resources:

  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 3

  CloudTrailBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
              - Sid: "AWSCloudTrailAclCheck"
                Effect: "Allow"
                Principal: 
                  Service: "cloudtrail.amazonaws.com"
                Action: "s3:GetBucketAcl"
                Resource: !Sub arn:aws:s3:::${CloudTrailBucket}

              - Sid: "AWSCloudTrailWrite"
                Effect: "Allow"
                Principal: 
                  Service: "cloudtrail.amazonaws.com"
                Action: "s3:PutObject"
                Resource: !Sub arn:aws:s3:::${CloudTrailBucket}/AWSLogs/${AWS::AccountId}/*
                Condition: 
                  StringEquals:
                    s3:x-amz-acl: "bucket-owner-full-control"

  CloudTrailConfig:
    DependsOn:
      - CloudTrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties:
      IsMultiRegionTrail: true
      IsLogging: true
      IncludeGlobalServiceEvents: true
      S3BucketName: !Ref CloudTrailBucket

  SumoRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${SumoLogicAccountID}:root
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId: !Ref SumoLogicId
      Path: "/"
      Policies:
      - PolicyName: SumoPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucketVersions
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${CloudTrailBucket}
              - !Sub arn:aws:s3:::${CloudTrailBucket}/*
Outputs:
  CloudTrailBucket:
    Description: ARN of bucket used to store CloudTrail logs
    Value: !GetAtt CloudTrailBucket.Arn
  SumoRoleARN:
    Description: ARN of the created role. Copy this ARN back to Sumo to complete the source creation process.
    Value: !GetAtt SumoRole.Arn
